### ISSUE TITLE
erreurs page video

### ISSUE THREAD

**Issue by FabienDaguet** [norsfinx/tutube#5]
Lignes: 

20, 26, 33, 49, 58, 87, 101, 115, 137, 152, 181, 

supprimer les espaces des images.

https://github.com/norsfinx/tutube/blob/61143165c65475a6d6cfd2fcd9b616071dd82417/videos.html#L54

Problème de fermeture de ton <a>

https://github.com/norsfinx/tutube/blob/61143165c65475a6d6cfd2fcd9b616071dd82417/videos.html#L58
https://github.com/norsfinx/tutube/blob/61143165c65475a6d6cfd2fcd9b616071dd82417/videos.html#L166
https://github.com/norsfinx/tutube/blob/61143165c65475a6d6cfd2fcd9b616071dd82417/videos.html#L168
https://github.com/norsfinx/tutube/blob/61143165c65475a6d6cfd2fcd9b616071dd82417/videos.html#L169
https://github.com/norsfinx/tutube/blob/61143165c65475a6d6cfd2fcd9b616071dd82417/videos.html#L195
https://github.com/norsfinx/tutube/blob/61143165c65475a6d6cfd2fcd9b616071dd82417/videos.html#L197
https://github.com/norsfinx/tutube/blob/61143165c65475a6d6cfd2fcd9b616071dd82417/videos.html#L198

Pas de balise fermante sur les img

https://github.com/norsfinx/tutube/blob/61143165c65475a6d6cfd2fcd9b616071dd82417/videos.html#L65

Div ouverte mais pas fermé.

https://github.com/norsfinx/tutube/blob/61143165c65475a6d6cfd2fcd9b616071dd82417/videos.html#L30

Ton article est ouvert mais pas fermé.

**Comment by norsfinx** [comment]
reste page tendance et video a faire
