### ISSUE TITLE
Quelques conseils d'un débutant

### ISSUE THREAD

**Issue by FabienDaguet** [norsfinx/tutube#6]
https://github.com/norsfinx/tutube/blob/61143165c65475a6d6cfd2fcd9b616071dd82417/index.html#L17

Pour ton header par exemple essaie de lui donner un nom de classe qui seras possible d'utiliser sur toutes les pages. 
Si jamais tu veux y apporter une modif tel que le background-color sur une autre page alors tu as comme solution de donner une deuxième classe à cette page.

exemple: 

     page index:

        <header class="header">
               ton contenu
        </header>

    2 ème page qui diffère

         <header class="header header--color"
                ton contenu
         </header>

du coup ton css 

.header {
     position: fixed;
        display: flex;
        justify-content: space-between;
        align-items: center;
        height: 36px;
        left: 0;
        right: 0;
        top: 0;
        padding: 10px;
        background: #FFFFFF;
        box-shadow: 0px 1px 4px rgba(0, 0, 0, 0.25);
        z-index: 1;
}

.header--color {
      background: #000000;
}

Tu gagne des lignes de codes et si jamais tu veux changer ta box-shadow par exemple tu as juste as changer sur header et pas a chercher ton autre header dans tes 1000 lignes de codes. Plus rapide. Valable pour tout.

https://github.com/norsfinx/tutube/blob/61143165c65475a6d6cfd2fcd9b616071dd82417/tendances.html#L34

Fais plus générique sur un titre du genre. 
Sur une selection tu peut avoir: sport, musique, nature...

Par exemple "selection-title"

Sinon en cas de changement de style tu devras le faire sur toutes tes classes différentes dans ton css au lieux de 1 classe.

Après pour améliorer rapidement tu peut changer la police, mettre un espace entre ton logo et ton titre dans le header, espacer un peu les icons du footer et mettre la bordure footer en shadow.

;)

**Comment by norsfinx** [comment]
c'est noté merci beaucoup.
